### ISSUE TITLE
Retard

### ISSUE THREAD

**Issue by HyperCold-xD** [zKaan/GTOSLatest#1]
Noob Kaan traitor be like: l3ak cuz 1m t00 pr0

**Comment by zKaan** [comment]
> Noob Kaan traitor be like: l3ak cuz 1m t00 pr0

Hi, same answer for you.
> Ah, sad... It was your problem to giving that source to everyone. I don't care. We all know that you guys were begging to me for fix that. I don't give a fuck. Other time don't give your source to lot of people.

I'm sorry if I prevented you from selling to people. :(
