### ISSUE TITLE
Retard

### ISSUE THREAD

**Issue by zLims** [zKaan/GTOSLatest#2]
Yeah, we supposed not to trust you. Retard skid.

**Comment by zKaan** [comment]
> Yeah, we supposed not to trust you. Retard skid.

Ah, sad... It was your problem to giving that source to everyone. I don't care. We all know that you guys were begging to me for fix that. I don't give a fuck. Other time don't give your source to lot of people.

**Comment by faraaj** [comment]
> Yeah, we supposed not to trust you. Retard skid.

shut the fuck up monkey
