### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by Purge-1** [zKaan/GTOSLatest#4]
**You have been posted sources that people have worked hard for, as he has DMCA on it since he didn't want it leaked you will be sued and reported to github official's.**

**Comment by zLims** [comment]
Agreed.

**Comment by CallMeTrust** [comment]
pro coder lim talked.

**Comment by zKaan** [comment]
Good luck then Mr. Anonymous pfp.

**Comment by Purge-1** [comment]
The "Mr. Anonymous pfp" is atleast not a braindead person leaked other people is stuff.

**Comment by zKaan** [comment]
it isn't, retard.

**Comment by zKaan** [comment]
we all know that you are a kid who wrote "I’m currently working on Python, Javascript,Ruby, TypeSceipt" to his github bio, but can't even code something.
