### ISSUE TITLE
setup?

### ISSUE THREAD

**Issue by HowToRuski** [zKaan/GTOSLatest#7]
can someone help me setting this server up? im having problems with errors...
or could anyone compile it and send me without-error version?

**Comment by huseyinhealth** [comment]
You should show the errors instead of asking for precompiled version.

**Comment by HowToRuski** [comment]
> You should show the errors instead of asking for precompiled version.

Cannot open source file: 'http.cpp': No such file or directory

for now it shows this one. and also it gives like 700 warnings.

**Comment by huseyinhealth** [comment]
I see. The source code doesn't have `http.cpp` anywhere... Author must know a solution, try contacting them.

**Comment by HowToRuski** [comment]
> I see. The source code doesn't have `http.cpp` anywhere... Author must know a solution, try contacting them.

Author is iniactive.

**Comment by huseyinhealth** [comment]
Their Discord account is Kaan#1337 . Try contacting them on Discord.

**Comment by HowToRuski** [comment]
> Their Discord account is Kaan#1337 . Try contacting them on Discord.

Also iniactive there.

**Comment by zKaan** [comment]
Hi, create a file called http.cpp or remove http.cpp from solution. I didn't upload it since it was empty.

**Comment by zKaan** [comment]
Also, for other issues, you can contact with me via discord, Kaan#1337

**Comment by iProgramMC** [comment]
Don't setup this garbage, write your own instead. It's going to save you a _looot_ of crashes from Sebia's misuse and torture of C++.
